## Code de florette (EN COURS)

En premier il y a le code pour la comparaison.

Aprés il y a plein d'autres trucs qui pourraient être utiles:
- des test de tokenisation
- des test de formation de n grams
- des tests d'utilisation de FastText (il en parle dans le paper dont le nom est marqué u peu plus bas) (c'est un fail)

Encore plus bas:
- des test de comparaisons sur plein de trucs (random, trus qui se ressemblent, grandes/petites phrases, synonymes) pour voir comment ça marche

#### Mount the Google Drive in order to access to the files which are located on our drive


In [ ]:
from google.colab import drive
drive._mount('/content/drive')

Mounted at /content/drive


#### Install and import every packages that will be necessary for the analysis

In [2]:
!pip install pickle-mixin
!pip install pyarrow
!pip install pathlib


import pyarrow
import pandas as pd
import numpy as np
import pathlib
from datetime import datetime
import sys
import bz2
import json
import pickle
import seaborn as sns
import matplotlib.pyplot as plt

### Imports, et import du model qu'on utilise ( pour l'instant all-MiniLM-L6-v2 )

In [1]:
#si besoin
#pip install -U sentence-transformers
#pip install gensim

In [48]:
#NLP libraries
import nltk
from nltk import word_tokenize
from gensim.models import FastText

In [156]:
from sklearn.metrics.pairwise import cosine_similarity

from sentence_transformers import SentenceTransformer

#import du model qu'on utilise, je prend all-MiniLM-L6-v2. là j'ai le model en local, mais on eut le prendre direct du net, c'est automoatisé (juste là au moment où je core il y à un bug généralisé, genre plus personne n'y a accès en ligne)
model = SentenceTransformer(r'C:\Users\flore\Desktop\EPFL\MA1\ada\PROJET\pretrained_model') #with model all-MiniLM-L6-v2' # or use 'bert-base-nli-mean-tokens'


### Comparaison des citations (morceau par morceau) aux expressions du paper, et création d'un dataframe avec qids, quote, sim_score_expression1, sim_score_expression2, ..., sim_score_expressionN.

Je decoupe les citations. Pour chaque expression: je compare chaque morceau de la citation avec l'expression, ça donne un score de similarité pour chaque morceau: on prend le max (ou bien faire un teshold ? à voir).  







#### Basé sur la technique du paper Sentence Similarity Techniques for Short vs Variable Length Text using Word Embeddings


#### Extract a small part of the whole quotes file to test (j'ai pas le vrai fichier pre procéssé, c'est pour ça qu'il y a des [ ] dans les citations, mais ça marchera pareil avec le bon fichier

In [17]:
#Extract a small part of the whole file to test 
path = r'C:\Users\flore\Desktop\EPFL\MA1\ada\PROJET\quotes-2020-precessed.json.bz2' #path de mon ordi
quotes = pd.DataFrame(columns=('qids','quotation'))
i = 0
with bz2.open(path, 'rb') as s_file:
  for instance in s_file:
    instance = json.loads(instance) 
    #print(instance)
    #print(instance['quotation'])
    i = i + 1
    quotes = quotes.append({'quoteID': instance['quoteID'], 'quotation': instance['quotation']}, ignore_index=True)
    #print(i)
    if i == 10:
      break

#### create a dataframe de test with the expression we want to compare, and their score (remplacer aprés avec le vrai)

In [41]:
#create a dataframe with the ewpression we want to compare, and their score
expressions = pd.DataFrame({'expression': ["I'm not sure", "I'dont know", "I'suppose", "I'think", "I'sure", "I'know"], 'expression_score': [2.91, 3.02, 3.34, 3.48, 6.02, 6.45]})
expressions.head(3)

expression  expression_score
0  I'm not sure              2.91
1   I'dont know              3.02
2     I'suppose              3.34

### Comparaison

#### Chunker les citations pour découper en un certain nombre de mots (j'ai pas trouvé de méthode optimale, alors je tokenize en mots, puis je join le nombre de mots qu'on veut

In [98]:
#First, create dataframe of the expressions tokenized and their confidence score
quotes_tokenized = pd.DataFrame(columns = ['quoteID','quote_token'])
for index, row in quotes.iterrows():
    quotes_tokenized = quotes_tokenized.append({'quoteID': row.quoteID, 'quote_token': nltk.word_tokenize(row.quotation)}, ignore_index=True)
quotes_tokenized.head(3)


quoteID                                        quote_token
0  2020-01-16-000088  [[, Department, of, Homeland, Security, ], was...
1  2020-01-24-000168  [[, I, met, them, ], when, they, just, turned,...
2  2020-01-17-000357  [[, The, delay, ], will, have, an, impact, [, ...

In [125]:
#Then reform chunk of n words

n = 4 #number of word in a chunk

quotes_chunks = pd.DataFrame(columns = ['quoteID','quote_chunks']) #initialize dataframe 


for index, row in quotes_tokenized.iterrows():
    lenght = len(row.quote_token) 
    list_chunk = []
    for i in range(lenght - n + 1):
        chunk = " ".join(row.quote_token[i : i+n-1])
        list_chunk.append(chunk)
    #print(list_chunk)
    #print('\n')
    quotes_chunks = quotes_chunks.append({'quoteID': row.quoteID, 'quote_chunks': list_chunk}, ignore_index=True)

        
quotes_chunks.head()
    
    

quoteID                                       quote_chunks
0  2020-01-16-000088  [[ Department of, Department of Homeland, of H...
1  2020-01-24-000168  [[ I met, I met them, met them ], them ] when,...
2  2020-01-17-000357  [[ The delay, The delay ], delay ] will, ] wil...
3  2020-04-02-000239  [[ The scheme, The scheme ], scheme ] treats, ...
4  2020-03-19-000276  [[ These ], These ] actions, ] actions will, a...

#### Compare the citations chunk with the expressions and add the comparison score = cosinus similarity (max score for the different chunk) in a new column

In [152]:
quotes_similarity = pd.DataFrame(columns=('qids','quotation', "I'm not sure", "I'dont know", "I'suppose", "I'think", "I'sure", "I'know"))
df_max_cos_sim = pd.DataFrame(index=("I'm not sure", "I'dont know", "I'suppose", "I'think", "I'sure", "I'know"))

for index, row in quotes_chunks.iterrows(): #itere sur les citations
    
    for index_exp, row_exp in expressions.iterrows(): #pour chaque expression
        list_cis_sim = [] #list des cosine similarity score pour tous les chunk (on gardera que le max)
        exp_to_compare = model.encode(row_exp.expression)
        
        for chunk in row.quote_chunks: #itere sur les chunk de citation
            chunk_to_compare = model.encode(chunk)
            cos_sim = cosine_similarity([chunk_to_compare], [exp_to_compare]) #absolument pas sure que je l'utilise comme il faut
            #print(cos_sim)
            list_cis_sim.append(cos_sim)
        
    max_cos_sim = max(list_cis_sim)
    df_max_cos_sim.loc[row_exp.expression, 0] = max_cos_sim
    
    quotes_similarity = quotes_similarity.append({'qids': row.quoteID, 'quotation': row.quote_chunks, "I'm not sure": df_max_cos_sim.loc["I'm not sure", 0], "I'dont know": df_max_cos_sim.loc["I'dont know", 0], "I'suppose": df_max_cos_sim.loc["I'suppose", 0], "I'think": df_max_cos_sim.loc["I'think", 0], "I'sure": df_max_cos_sim.loc["I'sure", 0], "I'know": df_max_cos_sim.loc["I'know", 0]}, ignore_index=True)

quotes_similarity.head()
        


qids                                          quotation  \
0  2020-01-16-000088  [[ Department of, Department of Homeland, of H...   
1  2020-01-24-000168  [[ I met, I met them, met them ], them ] when,...   
2  2020-01-17-000357  [[ The delay, The delay ], delay ] will, ] wil...   
3  2020-04-02-000239  [[ The scheme, The scheme ], scheme ] treats, ...   
4  2020-03-19-000276  [[ These ], These ] actions, ] actions will, a...   

   I'm not sure  I'dont know  I'suppose  I'think  I'sure    I'know  
0           NaN          NaN        NaN      NaN     NaN  0.199665  
1           NaN          NaN        NaN      NaN     NaN  0.249393  
2           NaN          NaN        NaN      NaN     NaN  0.336410  
3           NaN          NaN        NaN      NaN     NaN  0.294437  
4           NaN          NaN        NaN      NaN     NaN  0.217203

In [151]:
df_max_cos_sim

0
I'm not sure       NaN
I'dont know        NaN
I'suppose          NaN
I'think            NaN
I'sure             NaN
I'know        0.604759

### Autres trucs que j'ai pas utilisé mais qui peuvent être utile, genre tokenisation

#### Tokenisation of the expressions

In [46]:
#create dataframe of the expressions tokenized and their confidence score
expressions_tokenized = pd.DataFrame(columns = ['expression_token', 'score'])
for index, row in expressions.iterrows():
    expressions_tokenized = expressions_tokenized.append({'expression_token': nltk.word_tokenize(row.expression), 'score': row.expression_score}, ignore_index=True)
expressions_tokenized.head(3)


expression_token  score
0  [I, 'm, not, sure]   2.91
1      [I'dont, know]   3.02
2         [I'suppose]   3.34

#### Tokenisation of the quotations, en formant des n grams

In [97]:
from nltk import ngrams

n = 4 # n_gram
quotes_n_grams = pd.DataFrame(columns = ['quoteID', 'quote_n_grams'])

for index, row in quotes.iterrows():
    n_grams = ngrams(row.quotation.split(), n)
    quotes_n_grams = quotes_n_grams.append({'quoteID': row.quoteID, 'n_grams': n_grams},  ignore_index=True)
    
i = 0
for index, row in quotes_n_grams.iterrows():
    print(i)
    i=i+1
    for grams in row.n_grams:
        print(grams)
    if i > 1 : break


0
('[', 'Department', 'of', 'Homeland')
('Department', 'of', 'Homeland', 'Security')
('of', 'Homeland', 'Security', ']')
('Homeland', 'Security', ']', 'was')
('Security', ']', 'was', 'livid')
(']', 'was', 'livid', 'and')
('was', 'livid', 'and', 'strongly')
('livid', 'and', 'strongly', 'urged')
('and', 'strongly', 'urged', 'to')
('strongly', 'urged', 'to', 'have')
('urged', 'to', 'have', 'the')
('to', 'have', 'the', 'agenda')
('have', 'the', 'agenda', 'pulled.')
1
('[', 'I', 'met', 'them')
('I', 'met', 'them', ']')
('met', 'them', ']', 'when')
('them', ']', 'when', 'they')
(']', 'when', 'they', 'just')
('when', 'they', 'just', 'turned')
('they', 'just', 'turned', '4')
('just', 'turned', '4', 'and')
('turned', '4', 'and', '7.')
('4', 'and', '7.', 'They')
('and', '7.', 'They', 'were')
('7.', 'They', 'were', 'little.')
('They', 'were', 'little.', 'They')
('were', 'little.', 'They', 'felt')
('little.', 'They', 'felt', 'like')
('They', 'felt', 'like', 'my')
('felt', 'like', 'my', 'full-blown

### Trucs randoms, tests, code qui pourrait être utiles

#### exemples de truc pour faire des n grams

In [71]:
#exemple, not optimal, generate bigram and trigram

from nltk import ngrams
sentence = ['i have an apple', 'i like apples so much']

for i in range(len(sentence)):
    for n in range(2, 4):
        n_grams = ngrams(sentence[i].split(), n)
        for grams in n_grams:
            print(grams)

('i', 'have')
('have', 'an')
('an', 'apple')
('i', 'have', 'an')
('have', 'an', 'apple')
('i', 'like')
('like', 'apples')
('apples', 'so')
('so', 'much')
('i', 'like', 'apples')
('like', 'apples', 'so')
('apples', 'so', 'much')


In [75]:
#autre exemple de generatipn de bigram

input_list = ['all', 'this', 'happened', 'more', 'or', 'less']

def find_bigrams(input_list):
    bigram_list = []
    for i in range(len(input_list)-1):
        bigram_list.append((input_list[i], input_list[i+1]))
    return bigram_list

find_bigrams(input_list)

[('all', 'this'),
 ('this', 'happened'),
 ('happened', 'more'),
 ('more', 'or'),
 ('or', 'less')]

#### test d'utilisation de FastTest

In [70]:
#pip install fasttext-win

In [69]:
>>> import fasttext.util
>>> fasttext.util.download_model('en', if_exists='ignore')  # English
>>> ft = fasttext.load_model('cc.en.300.bin')

ModuleNotFoundError: No module named 'fasttext'

In [64]:
# Load pretrained fastText word embeddings python with gensim
from gensim.models.fasttext import load_facebook_model
pretrained_fastText_en = load_facebook_model('pretrined fastText model/cc.en.300.bin.gz')

FileNotFoundError: [Errno 2] No such file or directory: 'cc.en.300.bin.gz'

In [54]:
#en fait ça c'est pour trained un model, mais c'est pas ce qu'on veut faire ducoup
exp_model = FastText(expressions_tokenized.expression_token, vector_size=100, window=4, min_count=1, workers=4,sg=1)

In [61]:
#exp_model.wv['computer']

### Tests de comparaison : avec des trucs randoms, avec des citations

#### test de comparaison avec des trucs randoms

In [4]:
#test de comparaison semantique avec des trucs randoms

sentences = [
    "Three years later, the coffin was still full of Jello.",
    "The fish dreamed of escaping the fishbowl and into the toilet where he saw his friend go.",
    "The person box was packed with jelly many dozens of months later.",
    "He found a leprechaun in his walnut shell."
]

from sentence_transformers import SentenceTransformer

model = SentenceTransformer(r'C:\Users\flore\Desktop\EPFL\MA1\ada\PROJET\pretrained_model') #'bert-base-nli-mean-tokens'

sentence_embeddings = model.encode(sentences)

from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)

array([[0.22059387, 0.47637683, 0.22743046]], dtype=float32)

#### test de comparaison de quelques unes de nos citations entières avec les expressions. 

Ce n'est pas une bonnemethode, on va devoir découper les phrases en morceau.

In [8]:
#test de comparaison semantique de quelques une de nos citations avec une des phrases types du paper
#j'ai fait comme dans un exemple de BERT que j'ai trouvé sur internet. j'ai pris le pretrained model all-MiniLM-L6-v2


#note: normalement pas besoin d'avoir le model sur l'ordi, il suffit de mettre le nom 'all-MiniLM-L6-v2' et SentenceTransformer va le chercher tout seul sur internet, mais là il y a un bug genre ajd, 
#donc j'ai téléchargé le model sur mon ordi et mis le path
from sentence_transformers import SentenceTransformer
model = SentenceTransformer(r'C:\Users\flore\Desktop\EPFL\MA1\ada\PROJET\pretrained_model') #with model all-MiniLM-L6-v2' # or use 'bert-base-nli-mean-tokens'


#Extract a small part of the whole file to test 
path = r'C:\Users\flore\Desktop\EPFL\MA1\ada\PROJET\quotes-2020-precessed.json.bz2' #path de mon ordi
test = pd.DataFrame(columns=('qids','quotation'))
i = 0
with bz2.open(path, 'rb') as s_file:
  for instance in s_file:
    instance = json.loads(instance) 
    print(instance)
    #print(instance['quotation'])
    i = i + 1
    test = test.append({'quoteID': instance['quoteID'], 'quotation': instance['quotation']}, ignore_index=True)
    #print(i)
    if i == 10:
      break

#embedding des 10 citations
sentence_embeddings = model.encode(test['quotation'])

#comparaison avec une des phrase du paper: cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
to_compare = ["I'm sure it's"]
to_compare_embedding = model.encode(to_compare)

cosine_similarity(
    [to_compare_embedding[0]],
    sentence_embeddings[0:]
)

#l'output ets un array des coefficients de similarité (là ils osnt tous ba vu qu'aucune citation n'a un truc prche de I'm sure it's)

{'quoteID': '2020-01-16-000088', 'quotation': '[ Department of Homeland Security ] was livid and strongly urged to have the agenda pulled.', 'speaker': 'Sue Myrick'}
{'quoteID': '2020-01-24-000168', 'quotation': '[ I met them ] when they just turned 4 and 7. They were little. They felt like my full-blown stepkids.', 'speaker': 'Meghan King Edmonds'}
{'quoteID': '2020-01-17-000357', 'quotation': '[ The delay ] will have an impact [ on Slough ] but that might be mitigated by the fact we are going to have this Western Rail Link to Heathrow. It looks like that may come in sooner than Crossrail.', 'speaker': 'Dexter Smith'}
{'quoteID': '2020-04-02-000239', 'quotation': '[ The scheme ] treats addiction as an illness and the results so far have been extremely encouraging.', 'speaker': 'Barry Coppinger'}
{'quoteID': '2020-03-19-000276', 'quotation': '[ These ] actions will allow households who have an FHA-insured mortgage to meet the challenges of COVID-19 without fear of losing their homes, a

array([[ 0.01433591,  0.02702463,  0.04557954,  0.07573312, -0.02040301,
         0.09890234,  0.07345733,  0.0720223 ,  0.02289211,  0.05893324]],
      dtype=float32)

#### encore des tests pour voir si ça marche bien

In [22]:
#test de comparaison avec le début de la premiere citation pour checker qu'elle a alors bien un score élevé
to_compare_2 = ["Department of Homeland Security was livid and"]
to_compare_2_embedding = model.encode(to_compare_2)

cosine_similarity(
    [to_compare_2_embedding[0]],
    sentence_embeddings[0:]
)
#le premier est bien plus élevé

array([[0.7573065 , 0.02370122, 0.0167593 , 0.07905838, 0.12434015,
        0.13122094, 0.01477368, 0.07131456, 0.1100079 , 0.1029016 ]],
      dtype=float32)

In [29]:
#test de comparaison avec 2 trucs trés proches
to_compare_3 = ["I'm sure"]
to_compare_3_embedding = model.encode(to_compare_3)
sentence_2 = ["I'm sure it will be OK"]
sentence_2_embedding = model.encode(sentence_2)

cosine_similarity(
    [to_compare_3_embedding[0]],
    sentence_2_embedding[0:]
)

array([[0.17984062]], dtype=float32)

In [8]:
#test de comparaison avec 2 synonymes
to_compare_3 = ["I can be wrong"]
to_compare_3_embedding = model.encode(to_compare_3)
sentence_2 = ["I am mistaken coucou love"] #vrae faf feafq fezfaZF vzev ffreyhju j'ythgz azerazefg rt rt  r zeardcre grtuhy thzrg area etzttrh trhtrbg er ezt ery gt areer fraef dgc r e zger 
sentence_2_embedding = model.encode(sentence_2)

cosine_similarity(
    [to_compare_3_embedding[0]],
    sentence_2_embedding[0:]
)

array([[0.19524246]], dtype=float32)